before:
  hooks:
    - go mod download
monorepo:
  tag_prefix: cmd/builder/
  dir: .core/cmd/builder
version: 2
env:
  - COSIGN_YES=true
builds:
  - flags:
      - -trimpath
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64le
    ignore:
      - goos: windows
        goarch: arm64
    binary: ocb
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - johnpeterson785/opentelemetry-collector-builder:{{ .Version }}-amd64
      - johnpeterson785/opentelemetry-collector-builder:latest-amd64
    extra_files: 
      - builder-config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - johnpeterson785/opentelemetry-collector-builder:{{ .Version }}-arm64
      - johnpeterson785/opentelemetry-collector-builder:latest-arm64
    extra_files: 
      - builder-config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
  - goos: linux
    goarch: ppc64le
    dockerfile: Dockerfile
    image_templates:
      - johnpeterson785/opentelemetry-collector-builder:{{ .Version }}-ppc64le
      - johnpeterson785/opentelemetry-collector-builder:latest-ppc64le
    extra_files: 
      - builder-config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/ppc64le
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
  - goos: darwin
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - johnpeterson785/opentelemetry-collector-builder:{{ .Version }}-darwin-amd64
      - johnpeterson785/opentelemetry-collector-builder:latest-darwin-amd64
    extra_files: 
      - builder-config.yaml
    build_flag_templates:
      - --pull
      - --platform=darwin/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
  - goos: darwin
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - johnpeterson785/opentelemetry-collector-builder:{{ .Version }}-darwin-arm64
      - johnpeterson785/opentelemetry-collector-builder:latest-darwin-arm64
    extra_files: 
      - builder-config.yaml
    build_flag_templates:
      - --pull
      - --platform=darwin/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
  - goos: windows
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - johnpeterson785/opentelemetry-collector-builder:{{ .Version }}-windows-amd64
      - johnpeterson785/opentelemetry-collector-builder:latest-windows-amd64
    extra_files: 
      - builder-config.yaml
    build_flag_templates:
      - --pull
      - --platform=windows/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    use: buildx
docker_manifests:
  - name_template: johnpeterson785/opentelemetry-collector-builder:{{ .Version }}
    image_templates:
      - johnpeterson785/opentelemetry-collector-builder:{{ .Version }}-amd64
      - johnpeterson785/opentelemetry-collector-builder:{{ .Version }}-arm64
      - johnpeterson785/opentelemetry-collector-builder:{{ .Version }}-ppc64le
      - johnpeterson785/opentelemetry-collector-builder:{{ .Version }}-darwin-amd64
      - johnpeterson785/opentelemetry-collector-builder:{{ .Version }}-darwin-arm64
      - johnpeterson785/opentelemetry-collector-builder:{{ .Version }}-windows-amd64
  - name_template: johnpeterson785/opentelemetry-collector-builder:latest
      - johnpeterson785/opentelemetry-collector-builder:latest-amd64
      - johnpeterson785/opentelemetry-collector-builder:latest-arm64
      - johnpeterson785/opentelemetry-collector-builder:latest-ppc64le
      - johnpeterson785/opentelemetry-collector-builder:latest-darwin-amd64
      - johnpeterson785/opentelemetry-collector-builder:latest-darwin-arm64
      - johnpeterson785/opentelemetry-collector-builder:latest-windows-amd64
release:
  github:
    owner: jackgopack4
    name: opentelemetry-collector-releases
  header: |
    ### Images and binaries for collector distributions here: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/{{ .Tag }}
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  disable: true
